name: {{cookiecutter.framework_name}}

options:
  bundleIdPrefix: {{cookiecutter.bundle_id}}

configFiles:
  Debug: {{cookiecutter.framework_name}}/common_config.xcconfig
  Release: {{cookiecutter.framework_name}}/common_config.xcconfig


targets:
  {{cookiecutter.framework_name}}:
    type: framework
    platform: iOS
    sources: [{{cookiecutter.framework_name}}]
    settings:
      BUILD_LIBRARY_FOR_DISTRIBUTION: "YES"
    configFiles:
      Debug: {{cookiecutter.framework_name}}/common_config.xcconfig
      Release: {{cookiecutter.framework_name}}/common_config.xcconfig



schemes:
  {{cookiecutter.framework_name}}:
    build:
      targets:
        {{cookiecutter.framework_name}}: all
      postActions:
        - name: "Generate XCFramework"
          script: "( exec > /tmp/xcode_build_{{cookiecutter.framework_name}}.log 2>&1; cd $SRCROOT && ./build.sh )"
          settingsTarget: {{cookiecutter.framework_name}}
